[project]
name = "yuyi-speaker-diarization"
version = "0.1.0"
description = "Speaker diarization API using pyannote"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.104.0",
    "uvicorn[standard]>=0.24.0",
    "click>=8.1.0",
    "loguru>=0.7.0",
    "celery>=5.3.0",
    "redis>=5.0.0",
    "pydantic>=2.5.0",
    "python-dotenv>=1.0.0",
    "pyannote.audio>=3.1.0",
    "torch>=2.1.0",
    "torchaudio>=2.1.0",
    "aiofiles>=23.2.0",
    "pydantic-settings>=2.11.0",
    "python-multipart>=0.0.20",
    "httpx>=0.28.1",
    "huggingface-hub>=0.19.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.0",
    "pytest-asyncio>=0.21.0",
    "httpx>=0.25.0",
    "black>=23.0.0",
    "ruff>=0.1.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.black]
line-length = 88
target-version = ['py312']
